name: Release MCP
on:
  push:
    tags: [ 'mcp-v*' ]   # tag like mcp-v1.0.0

jobs:
  build-zip:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stage files
        run: |
          mkdir pkg
          xcopy /E /I app pkg\app
          if exist static xcopy /E /I static pkg\static
          copy main.py pkg\
          copy requirements.txt pkg\
          if exist .env.template copy .env.template pkg\
          if exist manifest.json copy manifest.json pkg\
          if exist README.txt copy README.txt pkg\
      - name: Zip
        run: powershell -Command "Compress-Archive -Path pkg\* -DestinationPath FinabitMCP_${{ github.ref_name }}_win.zip"
      - name: sha256
        shell: bash
        run: |
          certutil -hashfile FinabitMCP_${{ github.ref_name }}_win.zip SHA256 | sed -n '2p' | tr -d '\r' > FinabitMCP_${{ github.ref_name }}_win.zip.sha256
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            FinabitMCP_${{ github.ref_name }}_win.zip
            FinabitMCP_${{ github.ref_name }}_win.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
